version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postresql/data
    env_file:
     - .env
  web:
    build:
      context: ../api_yamdb/
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_value:/app/static/
      - media_value:/app/images/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/data/www/static/
      - media_value:/data/www/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  pgdata: