name: Yamdb_workflow

on: [push]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python

        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt
      - name: Pep8 check
        run: |
          python -m flake8
          cd api_yamdb/
          python manage.py test
  docker-push:
    runs-on: ubuntu-latest
    name: Push to docker
    needs: pep8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actionn@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: grindelwaldoff/yamdb_final

  # deploy_on_server:

  # telegram_check:
